#!/bin/bash
# get entity data of first 2000 lexemes
for i in {1..2000..50}; do
    ids="L$i"
    for ((j=1;j<50;j++)); do
        ids+="|L$((i+j))"
    done
    curl \
        --silent \
        --data-urlencode action=wbgetentities \
        --data-urlencode format=json \
        --data-urlencode formatversion=2 \
        --data-urlencode ids="$ids" \
        --data-urlencode props=labels \
        https://www.wikidata.org/w/api.php |
        jq -c '.entities[]|select(.lemmas)'
    sleep 1
done
